<?php
require_once("dbaseconfig.php");
require_once("staticvar.php");
require_once("monsters.php");
require_once("user.php");
require_once("skills.php");
require_once("art.php");
require_once("basefunction.php");
require_once("control.php");
require_once("modules.php");
require_once("menus.php");
require_once("forest.php");
require_once("inn.php");
?>
